#
###################################
# Site wide configuration
####################################
#
title: Manas Jain
email: manasjain0405@gmail.com
description: My Github Profile Page
url: # the base hostname & protocol for your site
keywords: ["portfolio", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Manas Jain
  avatar: profile.jpg
  job: "A learning computer engineer"
  bio: "Undergrad SGSITS, Indore | Robotics and A.I. Enthusiast | Avid Learner"
  email: manasjain0405@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: 
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: manasjain0405
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: manasjain0405
  skype: #username
  xing: #username
  instagram: 
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: 
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
